In [113]:
import pandas as pd
from sklearn import *

In [114]:
df=pd.read_csv('./cdata/train.csv')
df.head()

,order_status,price,freight_value,payment_type,payment_installments,payment_value,review_score,on_time_delivery,approval_time,demand_category,review_response_time
0,delivered,124.99,21.88,credit_card,2,146.87,4,1,0 days 00:16:37,High Demand,4 days 22:34:40
1,delivered,289.00,46.48,credit_card,8,335.48,5,1,0 days 00:10:08,Very High Demand,11 days 22:43:29
2,delivered,139.94,17.79,credit_card,7,157.73,5,0,1 days 00:11:25,High Demand,0 days 12:10:59
3,delivered,149.94,23.36,credit_card,1,173.30,5,1,0 days 01:22:41,High Demand,4 days 18:36:47
4,delivered,230.00,22.25,credit_card,8,252.25,5,1,0 days 00:18:39,Medium Demand,7 days 01:59:52

In [115]:
df.columns

Index(['order_status', 'price', 'freight_value', 'payment_type',
       'payment_installments', 'payment_value', 'review_score',
       'on_time_delivery', 'approval_time', 'demand_category',
       'review_response_time'],
      dtype='str')

In [116]:
df['order_status'].value_counts()

order_status
delivered      114844
shipped          1167
canceled          553
invoiced          370
processing        370
unavailable         7
approved            3
Name: count, dtype: int64

In [117]:
df_encoded = pd.get_dummies(df, columns=['order_status'], prefix='status',dtype=int)

In [118]:
df_encoded.head()

,price,freight_value,payment_type,payment_installments,payment_value,review_score,on_time_delivery,approval_time,demand_category,review_response_time,status_approved,status_canceled,status_delivered,status_invoiced,status_processing,status_shipped,status_unavailable
0,124.99,21.88,credit_card,2,146.87,4,1,0 days 00:16:37,High Demand,4 days 22:34:40,0,0,1,0,0,0,0
1,289.00,46.48,credit_card,8,335.48,5,1,0 days 00:10:08,Very High Demand,11 days 22:43:29,0,0,1,0,0,0,0
2,139.94,17.79,credit_card,7,157.73,5,0,1 days 00:11:25,High Demand,0 days 12:10:59,0,0,1,0,0,0,0
3,149.94,23.36,credit_card,1,173.30,5,1,0 days 01:22:41,High Demand,4 days 18:36:47,0,0,1,0,0,0,0
4,230.00,22.25,credit_card,8,252.25,5,1,0 days 00:18:39,Medium Demand,7 days 01:59:52,0,0,1,0,0,0,0

In [119]:
df_encoded['price'].dtypes

dtype('float64')

In [120]:
df_encoded['freight_value'].dtypes

dtype('float64')

In [121]:
df_encoded['payment_type'].value_counts()

payment_type
credit_card    86520
boleto         22820
voucher         6282
debit_card      1692
Name: count, dtype: int64

In [122]:
df_encoded = pd.get_dummies(df_encoded, columns=['payment_type'], prefix='pay',dtype=int)

In [123]:
df_encoded['extra_charge'] = df_encoded['payment_value'] - (df_encoded['price'] + df_encoded['freight_value'])

In [124]:
df_encoded.columns

Index(['price', 'freight_value', 'payment_installments', 'payment_value',
       'review_score', 'on_time_delivery', 'approval_time', 'demand_category',
       'review_response_time', 'status_approved', 'status_canceled',
       'status_delivered', 'status_invoiced', 'status_processing',
       'status_shipped', 'status_unavailable', 'pay_boleto', 'pay_credit_card',
       'pay_debit_card', 'pay_voucher', 'extra_charge'],
      dtype='str')

In [125]:
df_encoded['approval_time'] = pd.to_timedelta(df_encoded['approval_time'], errors='coerce')

df_encoded['approval_hours'] = df_encoded['approval_time'].dt.total_seconds() / 3600

df_encoded = df_encoded.drop(columns=['approval_time'])

In [126]:
df_encoded.columns

Index(['price', 'freight_value', 'payment_installments', 'payment_value',
       'review_score', 'on_time_delivery', 'demand_category',
       'review_response_time', 'status_approved', 'status_canceled',
       'status_delivered', 'status_invoiced', 'status_processing',
       'status_shipped', 'status_unavailable', 'pay_boleto', 'pay_credit_card',
       'pay_debit_card', 'pay_voucher', 'extra_charge', 'approval_hours'],
      dtype='str')

In [127]:
df_encoded['review_response_time'] = pd.to_timedelta(df_encoded['review_response_time'], errors='coerce')

df_encoded['review_response_time'] = df_encoded['review_response_time'].dt.total_seconds() / 3600

df_encoded = df_encoded.drop(columns=['review_response_time'])

In [128]:
df_encoded[['price', 'freight_value', 'payment_installments',
       'payment_value', 'review_score', 'on_time_delivery', 'demand_category',]]

,price,freight_value,payment_installments,payment_value,review_score,on_time_delivery,demand_category
0,124.99,21.88,2,146.87,4,1,High Demand
1,289.00,46.48,8,335.48,5,1,Very High Demand
2,139.94,17.79,7,157.73,5,0,High Demand
3,149.94,23.36,1,173.30,5,1,High Demand
4,230.00,22.25,8,252.25,5,1,Medium Demand
...,...,...,...,...,...,...,...
117309,74.90,13.88,6,88.78,4,1,Medium Demand
117310,114.90,14.16,3,129.06,5,1,Very High Demand
117311,37.00,19.04,5,56.04,1,0,Very High Demand
117312,689.00,22.07,2,711.07,5,1,Very High Demand
117313,13.99,7.78,1,21.77,5,1,High Demand

In [129]:
df_encoded = pd.get_dummies(df_encoded, columns=['demand_category'], prefix='demand',dtype=int)

In [130]:
df_encoded[['price', 'freight_value', 'payment_installments',
       'payment_value', 'review_score', 'on_time_delivery', ]]

,price,freight_value,payment_installments,payment_value,review_score,on_time_delivery
0,124.99,21.88,2,146.87,4,1
1,289.00,46.48,8,335.48,5,1
2,139.94,17.79,7,157.73,5,0
3,149.94,23.36,1,173.30,5,1
4,230.00,22.25,8,252.25,5,1
...,...,...,...,...,...,...
117309,74.90,13.88,6,88.78,4,1
117310,114.90,14.16,3,129.06,5,1
117311,37.00,19.04,5,56.04,1,0
117312,689.00,22.07,2,711.07,5,1
117313,13.99,7.78,1,21.77,5,1

In [131]:
df_encoded.columns

Index(['price', 'freight_value', 'payment_installments', 'payment_value',
       'review_score', 'on_time_delivery', 'status_approved',
       'status_canceled', 'status_delivered', 'status_invoiced',
       'status_processing', 'status_shipped', 'status_unavailable',
       'pay_boleto', 'pay_credit_card', 'pay_debit_card', 'pay_voucher',
       'extra_charge', 'approval_hours', 'demand_High Demand',
       'demand_Low Demand', 'demand_Medium Demand', 'demand_Very High Demand',
       'demand_Very Low Demand'],
      dtype='str')

In [132]:
df_encoded.dtypes

price                      float64
freight_value              float64
payment_installments         int64
payment_value              float64
review_score                 int64
on_time_delivery             int64
status_approved              int64
status_canceled              int64
status_delivered             int64
status_invoiced              int64
status_processing            int64
status_shipped               int64
status_unavailable           int64
pay_boleto                   int64
pay_credit_card              int64
pay_debit_card               int64
pay_voucher                  int64
extra_charge               float64
approval_hours             float64
demand_High Demand           int64
demand_Low Demand            int64
demand_Medium Demand         int64
demand_Very High Demand      int64
demand_Very Low Demand       int64
dtype: object

In [147]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# -----------------------------
# Step 1: Select relevant features
# -----------------------------

features = [
    'price',
    'freight_value',
    'payment_installments',
    'payment_value',
    'on_time_delivery',
    'approval_hours',
    'status_approved',
    'status_canceled',
    'status_delivered',
    'status_invoiced',
    'status_processing',
    'status_shipped',
    'status_unavailable',
    'pay_boleto',
    'pay_credit_card',
    'pay_debit_card',
    'pay_voucher',
    'extra_charge',
    'demand_High Demand',
    'demand_Low Demand',
    'demand_Medium Demand',
    'demand_Very High Demand',
    'demand_Very Low Demand'
]

X = df_encoded[features]

# Bad = 0 → review scores 1, 2
# Good = 1 → review scores 3, 4, 5
y = (df_encoded['review_score'] >= 3).astype(int)

# -----------------------------
# Step 2: Train/Test Split
# 70% Train / 30% Test
# -----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# -----------------------------
# Step 3: Feature Scaling
# -----------------------------

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# -----------------------------
# Step 4: Calculate Class Weights
# -----------------------------

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(zip(classes, weights))

print("Class Weights:")
print(class_weights)

# -----------------------------
# Step 5: Neural Network
# -----------------------------

model = keras.Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],)),

    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(16, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(8, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(1, activation='sigmoid')
])

# -----------------------------
# Step 6: Compile
# -----------------------------

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# -----------------------------
# Step 7: Train
# -----------------------------

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2,
    class_weight=class_weights,
    verbose=1
)

# -----------------------------
# Step 8: Evaluate
# -----------------------------

loss, accuracy = model.evaluate(
    X_test_scaled,
    y_test,
    verbose=0
)

print("\n" + "=" * 65)
print("TensorFlow/Keras Binary Classification - Class Weighted")
print("=" * 65)
print("Target: Bad (1,2) vs Good (3,4,5)")
print("Features: Order, Payment, Delivery, Status & Demand")
print("Train/Test Split: 70/30")
print("Stratified Split: Yes")
print("Feature Scaling: StandardScaler")
print("Architecture: 6 Hidden Dense Layers")
print("Hidden Activation: ReLU")
print("Dropout: 0.3")
print("Output Layer: 1 Neuron + Sigmoid")
print("Optimizer: Adam")
print("Loss Function: Binary Crossentropy")
print("Class Imbalance Handling: Balanced Class Weights")
print("Epochs: 10 | Batch Size: 32")
print(f"Test Accuracy: {accuracy:.4f}")
print("=" * 65)

# -----------------------------
# Step 9: Predictions
# -----------------------------

y_pred_prob = model.predict(
    X_test_scaled,
    verbose=0
)

y_pred = (y_pred_prob >= 0.5).astype(int).ravel()

# -----------------------------
# Step 10: Classification Report
# -----------------------------

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=['Bad', 'Good']
    )
)

Class Weights:
{np.int64(0): np.float64(3.09742757996379), np.int64(1): np.float64(0.596249074248871)}

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_56 (Dense)                │ (None, 256)            │         6,144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_48 (Dropout)            │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_57 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_49 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_58 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_50 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_59 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_51 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_60 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_52 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_61 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_53 (Dropout)            │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_62 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 50,049 (195.50 KB)

 Trainable params: 50,049 (195.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7412 - loss: 0.6313 - val_accuracy: 0.7934 - val_loss: 0.5852
Epoch 2/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7817 - loss: 0.6003 - val_accuracy: 0.7831 - val_loss: 0.5475
Epoch 3/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7710 - loss: 0.5934 - val_accuracy: 0.7818 - val_loss: 0.5617
Epoch 4/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7753 - loss: 0.5922 - val_accuracy: 0.7554 - val_loss: 0.5630
Epoch 5/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7706 - loss: 0.5890 - val_accuracy: 0.7869 - val_loss: 0.5581
Epoch 6/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7724 - loss: 0.5892 - val_accuracy: 0.7799 - val_loss: 0.5404
Epoch 7/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7676 - loss: 0.5885 - val_accuracy: 0.7599 - val_loss: 0.5627
Epoch 8/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7726 - loss: 0.5891 - val_accuracy: 0.7776 - val_loss: 0.5476
Epoch 9/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7690 - loss: 0.5882 - val_accuracy: 0.7786 - val_loss: 0.5440
Epoch 10/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7671 - loss: 0.5876 - val_accuracy: 0.7869 - val_loss: 0.5591

=================================================================
TensorFlow/Keras Binary Classification - Class Weighted
=================================================================
Target: Bad (1,2) vs Good (3,4,5)
Features: Order, Payment, Delivery, Status & Demand
Train/Test Split: 70/30
Stratified Split: Yes
Feature Scaling: StandardScaler
Architecture: 6 Hidden Dense Layers
Hidden Activation: ReLU
Dropout: 0.3
Output Layer: 1 Neuron + Sigmoid
Optimizer: Adam
Loss Function: Binary Crossentropy
Class Imbalance Handling: Balanced Class Weights
Epochs: 10 | Batch Size: 32
Test Accuracy: 0.7881
=================================================================

Classification Report:
              precision    recall  f1-score   support

         Bad       0.40      0.60      0.48      5682
        Good       0.91      0.82      0.87     29513

    accuracy                           0.79     35195
   macro avg       0.66      0.71      0.67     35195
weighted avg       0.83      0.79      0.80     35195

In [152]:
# -----------------------------
# Threshold = 0.7
# -----------------------------

threshold = 0.7

y_pred_prob = model.predict(
    X_test_scaled,
    verbose=0
)

y_pred = (y_pred_prob >= threshold).astype(int).ravel()

print("\n" + "=" * 65)
print("TensorFlow/Keras Binary Classification - Threshold 0.7")
print("=" * 65)
print("Target: Bad (1,2) vs Good (3,4,5)")
print("Classification Threshold: 0.7")
print("Class Weighting: Balanced")
print(f"Test Accuracy: {(y_pred == y_test).mean():.4f}")
print("=" * 65)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=['Bad', 'Good']
    )
)

=================================================================
TensorFlow/Keras Binary Classification - Threshold 0.7
=================================================================
Target: Bad (1,2) vs Good (3,4,5)
Classification Threshold: 0.7
Class Weighting: Balanced
Test Accuracy: 0.1614
=================================================================

Classification Report:
              precision    recall  f1-score   support

         Bad       0.16      1.00      0.28      5682
        Good       0.00      0.00      0.00     29513

    accuracy                           0.16     35195
   macro avg       0.08      0.50      0.14     35195
weighted avg       0.03      0.16      0.04     35195

f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [160]:
threshold = 0.39

y_pred_prob = model.predict(X_test_scaled, verbose=0).ravel()

y_pred = (y_pred_prob >= threshold).astype(int)

print("\n" + "=" * 65)
print(f"TensorFlow/Keras Binary Classification - Threshold {threshold}")
print("=" * 65)
print("Target: Bad (1,2) vs Good (3,4,5)")
print("Class Weighting: Balanced")
print(f"Classification Threshold: {threshold}")
print(f"Test Accuracy: {(y_pred == y_test).mean():.4f}")
print("=" * 65)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=['Bad', 'Good']
    )
)

=================================================================
TensorFlow/Keras Binary Classification - Threshold 0.39
=================================================================
Target: Bad (1,2) vs Good (3,4,5)
Class Weighting: Balanced
Classification Threshold: 0.39
Test Accuracy: 0.7968
=================================================================

Classification Report:
              precision    recall  f1-score   support

         Bad       0.41      0.58      0.48      5682
        Good       0.91      0.84      0.87     29513

    accuracy                           0.80     35195
   macro avg       0.66      0.71      0.68     35195
weighted avg       0.83      0.80      0.81     35195

In [164]:


# ============================================================
# Step 1: Select features related to customer review experience
# ============================================================

features = [
    'price',
    'freight_value',
    'payment_installments',
    'payment_value',

    # Delivery / order experience
    'on_time_delivery',
    'approval_hours',

    # Order status
    'status_approved',
    'status_canceled',
    'status_delivered',
    'status_invoiced',
    'status_processing',
    'status_shipped',
    'status_unavailable',

    # Payment method
    'pay_boleto',
    'pay_credit_card',
    'pay_debit_card',
    'pay_voucher',

    # Additional cost
    'extra_charge',

    # Demand
    'demand_High Demand',
    'demand_Low Demand',
    'demand_Medium Demand',
    'demand_Very High Demand',
    'demand_Very Low Demand'
]

X = df_encoded[features]

# ============================================================
# Step 2: Create binary target
# ============================================================

# Review scores:
# 1, 2     -> Bad  -> 0
# 3, 4, 5  -> Good -> 1

y = (df_encoded['review_score'] >= 4).astype(int)

# ============================================================
# Step 3: Train/Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# ============================================================
# Step 4: Feature Scaling
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ============================================================
# Step 5: Custom Class Weights
# ============================================================

# Increase the penalty for incorrectly predicting Bad as Good.
#
# Bad  -> weight 4.0
# Good -> weight 0.6
#
# The model will therefore pay much more attention to Bad cases.

class_weights = {
    0: 4.0,   # Bad
    1: 0.6    # Good
}

print("\nCustom Class Weights:")
print(class_weights)

# ============================================================
# Step 6: Neural Network
# ============================================================

model = keras.Sequential([

    layers.Input(shape=(X_train_scaled.shape[1],)),

    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(16, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(8, activation='relu'),
    layers.Dropout(0.3),

    # Binary output
    layers.Dense(1, activation='sigmoid')
])

# ============================================================
# Step 7: Compile
# ============================================================

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ============================================================
# Step 8: Train
# ============================================================

history = model.fit(
    X_train_scaled,
    y_train,

    epochs=10,
    batch_size=32,

    validation_split=0.5,

    # Use custom class weights
    class_weight=class_weights,

    verbose=1
)

# ============================================================
# Step 9: Evaluate
# ============================================================

loss, accuracy = model.evaluate(
    X_test_scaled,
    y_test,
    verbose=0
)

print("\n" + "=" * 70)
print("TensorFlow/Keras Binary Classification")
print("Custom Class Weights - Bad Focused")
print("=" * 70)

print("Target: Bad (1,2) vs Good (3,4,5)")
print("Bad = 0 | Good = 1")

print("Features: Order, Payment, Delivery, Status & Demand")

print("Train/Test Split: 70/30")
print("Stratified Split: Yes")

print("Feature Scaling: StandardScaler")

print("Architecture: 6 Hidden Dense Layers")
print("Hidden Activation: ReLU")
print("Dropout: 0.3")

print("Output Layer: 1 Neuron + Sigmoid")

print("Optimizer: Adam")
print("Loss Function: Binary Crossentropy")

print("Class Imbalance Handling: Custom Class Weights")
print("Bad Weight: 4.0")
print("Good Weight: 0.6")

print("Epochs: 10 | Batch Size: 32")

print(f"Test Accuracy: {accuracy:.4f}")

print("=" * 70)

# ============================================================
# Step 10: Predictions
# ============================================================

y_pred_prob = model.predict(
    X_test_scaled,
    verbose=0
).ravel()

# Standard threshold
threshold = 0.7

y_pred = (y_pred_prob >= threshold).astype(int)

# ============================================================
# Step 11: Classification Report
# ============================================================

print("\nClassification Threshold:", threshold)

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=['Bad', 'Good']
    )
)

Custom Class Weights:
{0: 4.0, 1: 0.6}
Epoch 1/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.2481 - loss: 0.8477 - val_accuracy: 0.2460 - val_loss: 0.8303
Epoch 2/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.2447 - loss: 0.8274 - val_accuracy: 0.2460 - val_loss: 0.8345
Epoch 3/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2447 - loss: 0.8203 - val_accuracy: 0.2460 - val_loss: 0.8152
Epoch 4/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2448 - loss: 0.8163 - val_accuracy: 0.2461 - val_loss: 0.8405
Epoch 5/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2477 - loss: 0.8144 - val_accuracy: 0.2462 - val_loss: 0.8298
Epoch 6/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.2481 - loss: 0.8133 - val_accuracy: 0.2478 - val_loss: 0.8234
Epoch 7/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2460 - loss: 0.8157 - val_accuracy: 0.2460 - val_loss: 0.8300
Epoch 8/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.2461 - loss: 0.8116 - val_accuracy: 0.2461 - val_loss: 0.8248
Epoch 9/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2452 - loss: 0.8119 - val_accuracy: 0.2464 - val_loss: 0.8248
Epoch 10/10
1284/1284 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.2456 - loss: 0.8110 - val_accuracy: 0.2461 - val_loss: 0.8245

======================================================================
TensorFlow/Keras Binary Classification
Custom Class Weights - Bad Focused
======================================================================
Target: Bad (1,2) vs Good (3,4,5)
Bad = 0 | Good = 1
Features: Order, Payment, Delivery, Status & Demand
Train/Test Split: 70/30
Stratified Split: Yes
Feature Scaling: StandardScaler
Architecture: 6 Hidden Dense Layers
Hidden Activation: ReLU
Dropout: 0.3
Output Layer: 1 Neuron + Sigmoid
Optimizer: Adam
Loss Function: Binary Crossentropy
Class Imbalance Handling: Custom Class Weights
Bad Weight: 4.0
Good Weight: 0.6
Epochs: 10 | Batch Size: 32
Test Accuracy: 0.2454
======================================================================

Classification Threshold: 0.7

Classification Report:
              precision    recall  f1-score   support

         Bad       0.25      1.00      0.39      8633
        Good       0.00      0.00      0.00     26562

    accuracy                           0.25     35195
   macro avg       0.12      0.50      0.20     35195
weighted avg       0.06      0.25      0.10     35195

f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [207]:
# ============================================================
# Step 1: Select meaningful features
# ============================================================

features = [
    'price',
    'freight_value',
    'extra_charge',
    'on_time_delivery'
]

X = df_encoded[features]


# ============================================================
# Step 2: Create 3-class target
# ============================================================

# Review score:
#
# 1, 2 -> Bad       -> 0
# 3    -> Undecided -> 1
# 4, 5 -> Good      -> 2

y = df_encoded['review_score'].map({
    1: 0,
    2: 0,
    3: 1,
    4: 2,
    5: 2
})


# ============================================================
# Step 3: Check class distribution
# ============================================================

print("\nClass Distribution:")
print(
    y.map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    }).value_counts()
)

print("\nClass Distribution (%):")
print(
    y.map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    }).value_counts(normalize=True) * 100
)


# ============================================================
# Step 4: Train/Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=10,
    stratify=y
)


# ============================================================
# Step 5: Feature Scaling
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# ============================================================
# Step 6: Balanced Class Weights
# ============================================================

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(
    zip(classes, weights)
)

print("\nBalanced Class Weights:")
print(class_weights)


# ============================================================
# Step 7: Neural Network
# ============================================================

model = keras.Sequential([

    layers.Input(
        shape=(X_train_scaled.shape[1],)
    ),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(16, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(8, activation='relu'),
    layers.Dropout(0.3),

    # 3-class output
    layers.Dense(3, activation='softmax')
])


# ============================================================
# Step 8: Compile
# ============================================================

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)


# ============================================================
# Step 9: Model Summary
# ============================================================

model.summary()


# ============================================================
# Step 10: Train
# ============================================================

history = model.fit(

    X_train_scaled,
    y_train,

    epochs=5,
    batch_size=32,

    validation_split=0.3,

    class_weight=class_weights,

    verbose=1
)


# ============================================================
# Step 11: Evaluate
# ============================================================

loss, accuracy = model.evaluate(
    X_test_scaled,
    y_test,
    verbose=0
)


print("\n" + "=" * 70)
print("TensorFlow/Keras Neural Network - 3 Class Classification")
print("Focused Customer-Experience Features")
print("=" * 70)

print("Target:")
print("1,2 -> Bad")
print("3   -> Undecided")
print("4,5 -> Good")

print("\nClass Encoding:")
print("Bad = 0")
print("Undecided = 1")
print("Good = 2")

print("\nFeatures Used:")
for feature in features:
    print(" -", feature)

print("\nTrain/Test Split: 70/30")
print("Stratified Split: Yes")

print("Feature Scaling: StandardScaler")

print("\nArchitecture:")
print("5 Hidden Dense Layers")
print("ReLU Activation")
print("Dropout: 0.3")

print("\nOutput Layer:")
print("3 Neurons + Softmax")

print("\nOptimizer: Adam")
print("Loss: Sparse Categorical Crossentropy")

print("\nClass Imbalance:")
print("Balanced Class Weights")
print(class_weights)

print("\nEpochs: 5")
print("Batch Size: 32")

print(f"\nTest Accuracy: {accuracy:.4f}")

print("=" * 70)


# ============================================================
# Step 12: Predictions
# ============================================================

y_pred_prob = model.predict(
    X_test_scaled,
    verbose=0
)

# Select class with highest probability
y_pred = np.argmax(
    y_pred_prob,
    axis=1
)


# ============================================================
# Step 13: Classification Report
# ============================================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            'Bad',
            'Undecided',
            'Good'
        ]
    )
)

Class Distribution:
review_score
Good         88537
Bad          18938
Undecided     9839
Name: count, dtype: int64

Class Distribution (%):
review_score
Good         75.470106
Bad          16.143001
Undecided     8.386893
Name: proportion, dtype: float64

Balanced Class Weights:
{np.int64(0): np.float64(2.0647959568529832), np.int64(1): np.float64(3.9745898068825323), np.int64(2): np.float64(0.4416780960064542)}

Model: "sequential_31"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_199 (Dense)               │ (None, 128)            │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_168 (Dropout)           │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_200 (Dense)               │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_169 (Dropout)           │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_201 (Dense)               │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_170 (Dropout)           │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_202 (Dense)               │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_171 (Dropout)           │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_203 (Dense)               │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_172 (Dropout)           │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_204 (Dense)               │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,667 (45.57 KB)

 Trainable params: 11,667 (45.57 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
1797/1797 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6684 - loss: 1.0468 - val_accuracy: 0.7192 - val_loss: 1.0018
Epoch 2/5
1797/1797 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6960 - loss: 1.0278 - val_accuracy: 0.7172 - val_loss: 0.9829
Epoch 3/5
1797/1797 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7027 - loss: 1.0247 - val_accuracy: 0.7085 - val_loss: 1.0029
Epoch 4/5
1797/1797 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7083 - loss: 1.0244 - val_accuracy: 0.7156 - val_loss: 0.9961
Epoch 5/5
1797/1797 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7049 - loss: 1.0213 - val_accuracy: 0.7157 - val_loss: 0.9946

======================================================================
TensorFlow/Keras Neural Network - 3 Class Classification
Focused Customer-Experience Features
======================================================================
Target:
1,2 -> Bad
3   -> Undecided
4,5 -> Good

Class Encoding:
Bad = 0
Undecided = 1
Good = 2

Features Used:
 - price
 - freight_value
 - extra_charge
 - on_time_delivery

Train/Test Split: 70/30
Stratified Split: Yes
Feature Scaling: StandardScaler

Architecture:
5 Hidden Dense Layers
ReLU Activation
Dropout: 0.3

Output Layer:
3 Neurons + Softmax

Optimizer: Adam
Loss: Sparse Categorical Crossentropy

Class Imbalance:
Balanced Class Weights
{np.int64(0): np.float64(2.0647959568529832), np.int64(1): np.float64(3.9745898068825323), np.int64(2): np.float64(0.4416780960064542)}

Epochs: 5
Batch Size: 32

Test Accuracy: 0.7099
======================================================================

Classification Report:
              precision    recall  f1-score   support

         Bad       0.37      0.64      0.47      5681
   Undecided       0.00      0.00      0.00      2952
        Good       0.84      0.80      0.82     26562

    accuracy                           0.71     35195
   macro avg       0.40      0.48      0.43     35195
weighted avg       0.70      0.71      0.70     35195

In [209]:
classification_report(
        y_test,
        y_pred,
        target_names=[
            'Bad',
            'Undecided',
            'Good'
        ]
    )

'              precision    recall  f1-score   support\n\n         Bad       0.37      0.64      0.47      5681\n   Undecided       0.00      0.00      0.00      2952\n        Good       0.84      0.80      0.82     26562\n\n    accuracy                           0.71     35195\n   macro avg       0.40      0.48      0.43     35195\nweighted avg       0.70      0.71      0.70     35195\n'

In [206]:
np.mean(y_pred)

np.float64(0.8552351186248046)

In [210]:
print("\nActual y_test:")
print(
    pd.Series(y_test)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)

print("\nPredicted y_pred:")
print(
    pd.Series(y_pred)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)

Actual y_test:
review_score
Good         26562
Bad           5681
Undecided     2952
Name: count, dtype: int64

Predicted y_pred:
Good         25284
Bad           9909
Undecided        2
Name: count, dtype: int64

In [211]:
# ============================================================
# Actual Review Score vs Predicted Class
# ============================================================

result = pd.DataFrame({
    'Actual Review Score': df_encoded.loc[X_test.index, 'review_score'],
    'Predicted Class': y_pred
})

result['Predicted Class'] = result['Predicted Class'].map({
    0: 'Bad',
    1: 'Undecided',
    2: 'Good'
})

print("\nActual Review Score vs Predicted Class:")
print(
    pd.crosstab(
        result['Actual Review Score'],
        result['Predicted Class']
    )
)

Actual Review Score vs Predicted Class:
Predicted Class       Bad   Good  Undecided
Actual Review Score
1                    3062   1405          2
2                     602    610          0
3                    1005   1947          0
4                    1422   5229          0
5                    3818  16093          0

In [212]:
df_encoded.columns

Index(['price', 'freight_value', 'payment_installments', 'payment_value',
       'review_score', 'on_time_delivery', 'status_approved',
       'status_canceled', 'status_delivered', 'status_invoiced',
       'status_processing', 'status_shipped', 'status_unavailable',
       'pay_boleto', 'pay_credit_card', 'pay_debit_card', 'pay_voucher',
       'extra_charge', 'approval_hours', 'demand_High Demand',
       'demand_Low Demand', 'demand_Medium Demand', 'demand_Very High Demand',
       'demand_Very Low Demand'],
      dtype='str')

In [213]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.utils.class_weight import compute_class_weight

import numpy as np
import pandas as pd


# ============================================================
# Step 1: Use all available features
# ============================================================

features = [
    'price',
    'freight_value',
    'payment_installments',
    'payment_value',
    'on_time_delivery',
    'status_approved',
    'status_canceled',
    'status_delivered',
    'status_invoiced',
    'status_processing',
    'status_shipped',
    'status_unavailable',
    'pay_boleto',
    'pay_credit_card',
    'pay_debit_card',
    'pay_voucher',
    'extra_charge',
    'approval_hours',
    'demand_High Demand',
    'demand_Low Demand',
    'demand_Medium Demand',
    'demand_Very High Demand',
    'demand_Very Low Demand'
]

X = df_encoded[features]


# ============================================================
# Step 2: Create 3-class target
# ============================================================

# 1,2 -> Bad       -> 0
# 3   -> Undecided -> 1
# 4,5 -> Good      -> 2

y = df_encoded['review_score'].map({
    1: 0,
    2: 0,
    3: 1,
    4: 2,
    5: 2
})


# ============================================================
# Step 3: Check class distribution
# ============================================================

print("\nActual Class Distribution:")

print(
    y.map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    }).value_counts()
)


# ============================================================
# Step 4: Train/Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=10,
    stratify=y
)


# ============================================================
# Step 5: Scale features
# ============================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# ============================================================
# Step 6: Balanced class weights
# ============================================================

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(
    zip(classes, weights)
)

print("\nBalanced Class Weights:")
print(class_weights)


# ============================================================
# Step 7: Neural Network
# ============================================================

model = keras.Sequential([

    layers.Input(
        shape=(X_train_scaled.shape[1],)
    ),

    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(16, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(8, activation='relu'),
    layers.Dropout(0.3),

    # 3 classes
    layers.Dense(3, activation='softmax')
])


# ============================================================
# Step 8: Compile
# ============================================================

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)


# ============================================================
# Step 9: Train
# ============================================================

history = model.fit(

    X_train_scaled,
    y_train,

    epochs=10,
    batch_size=32,

    validation_split=0.2,

    class_weight=class_weights,

    verbose=1
)


# ============================================================
# Step 10: Evaluate
# ============================================================

loss, accuracy = model.evaluate(
    X_test_scaled,
    y_test,
    verbose=0
)


print("\n" + "=" * 70)
print("TensorFlow/Keras 3-Class Classification")
print("Full Feature Set")
print("=" * 70)

print("Target:")
print("1,2 -> Bad")
print("3   -> Undecided")
print("4,5 -> Good")

print("\nFeatures Used:", len(features))

print("Train/Test Split: 70/30")
print("Stratified Split: Yes")

print("Feature Scaling: StandardScaler")

print("\nArchitecture:")
print("6 Hidden Dense Layers")
print("ReLU Activation")
print("Dropout: 0.3")

print("\nOutput Layer:")
print("3 Neurons + Softmax")

print("\nOptimizer: Adam")
print("Loss: Sparse Categorical Crossentropy")

print("\nClass Imbalance:")
print("Balanced Class Weights")
print(class_weights)

print("\nEpochs: 10")
print("Batch Size: 32")

print(f"\nTest Accuracy: {accuracy:.4f}")

print("=" * 70)


# ============================================================
# Step 11: Predictions
# ============================================================

y_pred_prob = model.predict(
    X_test_scaled,
    verbose=0
)

y_pred = np.argmax(
    y_pred_prob,
    axis=1
)


# ============================================================
# Step 12: Classification Report
# ============================================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            'Bad',
            'Undecided',
            'Good'
        ]
    )
)


# ============================================================
# Step 13: Actual vs Predicted Distribution
# ============================================================

print("\nActual y_test distribution:")

print(
    pd.Series(y_test)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)


print("\nPredicted y_pred distribution:")

print(
    pd.Series(y_pred)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)


# ============================================================
# Step 14: Actual Review Score vs Predicted Class
# ============================================================

result = pd.DataFrame({

    'Actual Review Score':
        df_encoded.loc[
            X_test.index,
            'review_score'
        ],

    'Predicted Class':
        y_pred

})

result['Predicted Class'] = result[
    'Predicted Class'
].map({
    0: 'Bad',
    1: 'Undecided',
    2: 'Good'
})


print("\nActual Review Score vs Predicted Class:")

print(
    pd.crosstab(
        result['Actual Review Score'],
        result['Predicted Class']
    )
)

Actual Class Distribution:
review_score
Good         88537
Bad          18938
Undecided     9839
Name: count, dtype: int64

Balanced Class Weights:
{np.int64(0): np.float64(2.0647959568529832), np.int64(1): np.float64(3.9745898068825323), np.int64(2): np.float64(0.4416780960064542)}
Epoch 1/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.5595 - loss: 1.0521 - val_accuracy: 0.7467 - val_loss: 0.9887
Epoch 2/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.6498 - loss: 1.0305 - val_accuracy: 0.7178 - val_loss: 1.0036
Epoch 3/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.6772 - loss: 1.0240 - val_accuracy: 0.7204 - val_loss: 0.9822
Epoch 4/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.6851 - loss: 1.0224 - val_accuracy: 0.7357 - val_loss: 0.9778
Epoch 5/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6937 - loss: 1.0194 - val_accuracy: 0.7241 - val_loss: 0.9679
Epoch 6/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6926 - loss: 1.0194 - val_accuracy: 0.7213 - val_loss: 0.9838
Epoch 7/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6892 - loss: 1.0188 - val_accuracy: 0.7225 - val_loss: 0.9702
Epoch 8/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6873 - loss: 1.0197 - val_accuracy: 0.7056 - val_loss: 0.9899
Epoch 9/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6917 - loss: 1.0179 - val_accuracy: 0.7244 - val_loss: 0.9772
Epoch 10/10
2053/2053 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6887 - loss: 1.0183 - val_accuracy: 0.7231 - val_loss: 0.9637

======================================================================
TensorFlow/Keras 3-Class Classification
Full Feature Set
======================================================================
Target:
1,2 -> Bad
3   -> Undecided
4,5 -> Good

Features Used: 23
Train/Test Split: 70/30
Stratified Split: Yes
Feature Scaling: StandardScaler

Architecture:
6 Hidden Dense Layers
ReLU Activation
Dropout: 0.3

Output Layer:
3 Neurons + Softmax

Optimizer: Adam
Loss: Sparse Categorical Crossentropy

Class Imbalance:
Balanced Class Weights
{np.int64(0): np.float64(2.0647959568529832), np.int64(1): np.float64(3.9745898068825323), np.int64(2): np.float64(0.4416780960064542)}

Epochs: 10
Batch Size: 32

Test Accuracy: 0.7167
======================================================================

Classification Report:
              precision    recall  f1-score   support

         Bad       0.38      0.63      0.47      5681
   Undecided       0.00      0.00      0.00      2952
        Good       0.84      0.81      0.83     26562

    accuracy                           0.72     35195
   macro avg       0.41      0.48      0.43     35195
weighted avg       0.70      0.72      0.70     35195


Actual y_test distribution:
review_score
Good         26562
Bad           5681
Undecided     2952
Name: count, dtype: int64

Predicted y_pred distribution:
Good    25736
Bad      9459
Name: count, dtype: int64

Actual Review Score vs Predicted Class:
Predicted Class       Bad   Good
Actual Review Score
1                    2998   1471
2                     579    633
3                     966   1986
4                    1342   5309
5                    3574  16337

f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
f:\mlProjects\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [214]:
import lightgbm as lgb
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score


# ============================================================
# Step 1: Use all available features
# ============================================================

features = [
    'price',
    'freight_value',
    'payment_installments',
    'payment_value',
    'on_time_delivery',
    'status_approved',
    'status_canceled',
    'status_delivered',
    'status_invoiced',
    'status_processing',
    'status_shipped',
    'status_unavailable',
    'pay_boleto',
    'pay_credit_card',
    'pay_debit_card',
    'pay_voucher',
    'extra_charge',
    'approval_hours',
    'demand_High Demand',
    'demand_Low Demand',
    'demand_Medium Demand',
    'demand_Very High Demand',
    'demand_Very Low Demand'
]

X = df_encoded[features]


# ============================================================
# Step 2: Create 3-class target
# ============================================================

# 1,2 -> Bad       -> 0
# 3   -> Undecided -> 1
# 4,5 -> Good      -> 2

y = df_encoded['review_score'].map({
    1: 0,
    2: 0,
    3: 1,
    4: 2,
    5: 2
})


# ============================================================
# Step 3: Train/Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=10,
    stratify=y
)


# ============================================================
# Step 4: LightGBM Model
# ============================================================

model = lgb.LGBMClassifier(
    objective='multiclass',
    num_class=3,

    n_estimators=300,
    learning_rate=0.05,

    num_leaves=31,
    max_depth=-1,

    subsample=0.8,
    colsample_bytree=0.8,

    random_state=10,
    n_jobs=-1
)


# ============================================================
# Step 5: Train
# ============================================================

model.fit(
    X_train,
    y_train
)


# ============================================================
# Step 6: Predictions
# ============================================================

y_pred = model.predict(X_test)


# ============================================================
# Step 7: Results
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\n" + "=" * 70)
print("LightGBM Multiclass Classification")
print("Tree-Based Model")
print("=" * 70)

print("Target:")
print("1,2 -> Bad")
print("3   -> Undecided")
print("4,5 -> Good")

print("\nFeatures Used:", len(features))

print("Train/Test Split: 70/30")
print("Stratified Split: Yes")

print("\nModel:")
print("LightGBM Gradient Boosted Decision Trees")
print("Objective: Multiclass")
print("Number of Classes: 3")

print("Estimators: 300")
print("Learning Rate: 0.05")
print("Number of Leaves: 31")
print("Subsample: 0.8")
print("Column Sampling: 0.8")

print(f"\nTest Accuracy: {accuracy:.4f}")

print("=" * 70)


# ============================================================
# Step 8: Classification Report
# ============================================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            'Bad',
            'Undecided',
            'Good'
        ]
    )
)


# ============================================================
# Step 9: Actual vs Predicted Distribution
# ============================================================

print("\nActual Distribution:")

print(
    pd.Series(y_test)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)


print("\nPredicted Distribution:")

print(
    pd.Series(y_pred)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)


# ============================================================
# Step 10: Actual Review Score vs Predicted Class
# ============================================================

result = pd.DataFrame({
    'Actual Review Score':
        df_encoded.loc[
            X_test.index,
            'review_score'
        ],

    'Predicted Class':
        y_pred
})

result['Predicted Class'] = result[
    'Predicted Class'
].map({
    0: 'Bad',
    1: 'Undecided',
    2: 'Good'
})


print("\nActual Review Score vs Predicted Class:")

print(
    pd.crosstab(
        result['Actual Review Score'],
        result['Predicted Class']
    )
)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002168 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1327
[LightGBM] [Info] Number of data points in the train set: 82119, number of used features: 21
[LightGBM] [Info] Start training from score -1.823644
[LightGBM] [Info] Start training from score -2.478534
[LightGBM] [Info] Start training from score -0.281438

======================================================================
LightGBM Multiclass Classification
Tree-Based Model
======================================================================
Target:
1,2 -> Bad
3   -> Undecided
4,5 -> Good

Features Used: 23
Train/Test Split: 70/30
Stratified Split: Yes

Model:
LightGBM Gradient Boosted Decision Trees
Objective: Multiclass
Number of Classes: 3
Estimators: 300
Learning Rate: 0.05
Number of Leaves: 31
Subsample: 0.8
Column Sampling: 0.8

Test Accuracy: 0.7973
======================================================================

Classification Report:
              precision    recall  f1-score   support

         Bad       0.66      0.39      0.49      5681
   Undecided       0.94      0.02      0.04      2952
        Good       0.81      0.97      0.88     26562

    accuracy                           0.80     35195
   macro avg       0.80      0.46      0.47     35195
weighted avg       0.80      0.80      0.75     35195


Actual Distribution:
review_score
Good         26562
Bad           5681
Undecided     2952
Name: count, dtype: int64

Predicted Distribution:
Good         31715
Bad           3410
Undecided       70
Name: count, dtype: int64

Actual Review Score vs Predicted Class:
Predicted Class       Bad   Good  Undecided
Actual Review Score
1                    1944   2524          1
2                     292    918          2
3                     371   2515         66
4                     291   6360          0
5                     512  19398          1

In [215]:
importance = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    'Importance',
    ascending=False
)

print("\nLightGBM Feature Importance:")
print(importance)

LightGBM Feature Importance:
                    Feature  Importance
17           approval_hours        5514
1             freight_value        5144
0                     price        4760
3             payment_value        3826
16             extra_charge        3711
2      payment_installments        1437
21  demand_Very High Demand         482
18       demand_High Demand         380
4          on_time_delivery         333
20     demand_Medium Demand         233
13          pay_credit_card         218
15              pay_voucher         162
12               pay_boleto         160
19        demand_Low Demand         152
7          status_delivered         106
9         status_processing          94
10           status_shipped          79
14           pay_debit_card          64
6           status_canceled          55
22   demand_Very Low Demand          54
8           status_invoiced          36
5           status_approved           0
11       status_unavailable           0

In [216]:
import lightgbm as lgb
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score


# ============================================================
# Step 1: Create better delivery / experience features
# ============================================================

df = df_encoded.copy()

# Convert datetime columns if they exist
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')


# ------------------------------------------------------------
# Approval time
# ------------------------------------------------------------

if (
    'order_purchase_timestamp' in df.columns
    and 'order_approved_at' in df.columns
):
    df['approval_hours_new'] = (
        df['order_approved_at']
        - df['order_purchase_timestamp']
    ).dt.total_seconds() / 3600


# ------------------------------------------------------------
# Actual delivery duration
# ------------------------------------------------------------

if (
    'order_purchase_timestamp' in df.columns
    and 'order_delivered_customer_date' in df.columns
):
    df['delivery_days'] = (
        df['order_delivered_customer_date']
        - df['order_purchase_timestamp']
    ).dt.total_seconds() / 86400


# ------------------------------------------------------------
# Delivery delay
#
# Positive = late
# Negative = early
# Zero     = exactly on time
# ------------------------------------------------------------

if (
    'order_delivered_customer_date' in df.columns
    and 'order_estimated_delivery_date' in df.columns
):
    df['delivery_delay_days'] = (
        df['order_delivered_customer_date']
        - df['order_estimated_delivery_date']
    ).dt.total_seconds() / 86400


# ------------------------------------------------------------
# Carrier shipping time
# ------------------------------------------------------------

if (
    'order_delivered_carrier_date' in df.columns
    and 'order_delivered_customer_date' in df.columns
):
    df['carrier_to_customer_days'] = (
        df['order_delivered_customer_date']
        - df['order_delivered_carrier_date']
    ).dt.total_seconds() / 86400


# ============================================================
# Step 2: Select features
# ============================================================

features = [
    # Cost
    'price',
    'freight_value',
    'payment_value',
    'payment_installments',
    'extra_charge',

    # Existing experience feature
    'on_time_delivery',
    'approval_hours',

    # NEW delivery features
    'approval_hours_new',
    'delivery_days',
    'delivery_delay_days',
    'carrier_to_customer_days',

    # Demand
    'demand_High Demand',
    'demand_Low Demand',
    'demand_Medium Demand',
    'demand_Very High Demand',
    'demand_Very Low Demand',

    # Payment
    'pay_boleto',
    'pay_credit_card',
    'pay_debit_card',
    'pay_voucher',

    # Status
    'status_canceled',
    'status_delivered',
    'status_processing',
    'status_shipped',
    'status_invoiced',
    'status_approved',
    'status_unavailable'
]


# Keep only columns that actually exist
features = [
    col for col in features
    if col in df.columns
]

X = df[features].copy()


# ============================================================
# Step 3: Handle missing values
# ============================================================

X = X.replace(
    [float('inf'), float('-inf')],
    pd.NA
)

X = X.fillna(
    X.median(numeric_only=True)
)


# ============================================================
# Step 4: Create target
# ============================================================

# 1,2 -> Bad       = 0
# 3   -> Undecided = 1
# 4,5 -> Good      = 2

y = df['review_score'].map({
    1: 0,
    2: 0,
    3: 1,
    4: 2,
    5: 2
})


# Remove rows where target is missing
valid = y.notna()

X = X.loc[valid]
y = y.loc[valid]


# ============================================================
# Step 5: Train/Test Split
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=10,
    stratify=y
)


# ============================================================
# Step 6: LightGBM
# ============================================================

model = lgb.LGBMClassifier(
    objective='multiclass',
    num_class=3,

    n_estimators=300,
    learning_rate=0.05,

    num_leaves=31,
    max_depth=-1,

    subsample=0.8,
    colsample_bytree=0.8,

    class_weight={
        0: 2.0,   # Bad
        1: 4.0,   # Undecided
        2: 0.5    # Good
    },

    random_state=10,
    n_jobs=-1
)


# ============================================================
# Step 7: Train
# ============================================================

model.fit(
    X_train,
    y_train
)


# ============================================================
# Step 8: Predict
# ============================================================

y_pred = model.predict(X_test)


# ============================================================
# Step 9: Results
# ============================================================

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("\n" + "=" * 75)
print("LightGBM Multiclass Classification")
print("Enhanced Customer-Experience Features")
print("=" * 75)

print("Target:")
print("1,2 -> Bad")
print("3   -> Undecided")
print("4,5 -> Good")

print("\nFeatures Used:", len(features))

print("\nNew Experience Features:")

for feature in [
    'approval_hours_new',
    'delivery_days',
    'delivery_delay_days',
    'carrier_to_customer_days'
]:
    if feature in features:
        print(" -", feature)

print("\nTrain/Test Split: 70/30")
print("Stratified Split: Yes")

print("\nModel:")
print("LightGBM Gradient Boosted Decision Trees")
print("Objective: Multiclass")
print("Classes: 3")

print("\nClass Weights:")
print({
    'Bad': 2.0,
    'Undecided': 4.0,
    'Good': 0.5
})

print("\nEstimators: 300")
print("Learning Rate: 0.05")
print("Number of Leaves: 31")

print(f"\nTest Accuracy: {accuracy:.4f}")

print("=" * 75)


# ============================================================
# Step 10: Classification Report
# ============================================================

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            'Bad',
            'Undecided',
            'Good'
        ]
    )
)


# ============================================================
# Step 11: Prediction Distribution
# ============================================================

print("\nActual Distribution:")

print(
    pd.Series(y_test)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)


print("\nPredicted Distribution:")

print(
    pd.Series(y_pred)
    .map({
        0: 'Bad',
        1: 'Undecided',
        2: 'Good'
    })
    .value_counts()
)


# ============================================================
# Step 12: Actual Rating vs Prediction
# ============================================================

result = pd.DataFrame({
    'Actual Review Score':
        df.loc[
            X_test.index,
            'review_score'
        ],

    'Predicted Class':
        y_pred
})

result['Predicted Class'] = result[
    'Predicted Class'
].map({
    0: 'Bad',
    1: 'Undecided',
    2: 'Good'
})


print("\nActual Review Score vs Predicted Class:")

print(
    pd.crosstab(
        result['Actual Review Score'],
        result['Predicted Class']
    )
)


# ============================================================
# Step 13: Feature Importance
# ============================================================

importance = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    'Importance',
    ascending=False
)

print("\nLightGBM Feature Importance:")

print(importance.to_string(index=False))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002228 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1327
[LightGBM] [Info] Number of data points in the train set: 82119, number of used features: 21
[LightGBM] [Info] Start training from score -1.165561
[LightGBM] [Info] Start training from score -1.127304
[LightGBM] [Info] Start training from score -1.009650

===========================================================================
LightGBM Multiclass Classification
Enhanced Customer-Experience Features
===========================================================================
Target:
1,2 -> Bad
3   -> Undecided
4,5 -> Good

Features Used: 23

New Experience Features:

Train/Test Split: 70/30
Stratified Split: Yes

Model:
LightGBM Gradient Boosted Decision Trees
Objective: Multiclass
Classes: 3

Class Weights:
{'Bad': 2.0, 'Undecided': 4.0, 'Good': 0.5}

Estimators: 300
Learning Rate: 0.05
Number of Leaves: 31

Test Accuracy: 0.7279
===========================================================================

Classification Report:
              precision    recall  f1-score   support

         Bad       0.44      0.62      0.52      5681
   Undecided       0.25      0.15      0.19      2952
        Good       0.85      0.82      0.83     26562

    accuracy                           0.73     35195
   macro avg       0.51      0.53      0.51     35195
weighted avg       0.73      0.73      0.73     35195


Actual Distribution:
review_score
Good         26562
Bad           5681
Undecided     2952
Name: count, dtype: int64

Predicted Distribution:
Good         25481
Bad           7926
Undecided     1788
Name: count, dtype: int64

Actual Review Score vs Predicted Class:
Predicted Class       Bad   Good  Undecided
Actual Review Score
1                    2958   1372        139
2                     567    602         43
3                     656   1855        441
4                    1052   5306        293
5                    2693  16346        872

LightGBM Feature Importance:
                Feature  Importance
         approval_hours        5705
          freight_value        5029
                  price        4490
          payment_value        4089
           extra_charge        3537
   payment_installments        1448
demand_Very High Demand         420
     demand_High Demand         382
       on_time_delivery         378
   demand_Medium Demand         244
        pay_credit_card         223
            pay_voucher         174
       status_delivered         165
             pay_boleto         161
      demand_Low Demand         157
      status_processing          90
         pay_debit_card          81
 demand_Very Low Demand          70
         status_shipped          62
        status_canceled          59
        status_invoiced          36
        status_approved           0
     status_unavailable           0